### PR TITLE
muqss fixes for 4.12-ck

### PR DESCRIPTION
**Pull request by sergey-senozhatsky**

### CODE REVIEW

**Comment by ckolivas** [comment]
while (42) is a forever loop.

**Comment by sergey-senozhatsky** [comment]
shame on me! while(42)....... indeed.

**Comment by sergey-senozhatsky** [comment]
any idea on why do I see those lockdep assertions then?

**Comment by ckolivas** [comment]
Since we intentionally switch runqueue locks in do_set_cpus_allowed it probably breaks lockdep and I'm guessing needs fudging to convince lockdep it's okay.

**Comment by sergey-senozhatsky** [comment]
ok. the mainline does  rq_pin_lock(rq, rf)  in __task_rq_lock(),
which, ends up doing

```
 915 static inline void rq_pin_lock(struct rq *rq, struct rq_flags *rf)                                                                                                                                                                                                                                                        
 916 {                                                                               
 917         rf->cookie = lockdep_pin_lock(&rq->lock);                               
 918                                                                                 
 919 #ifdef CONFIG_SCHED_DEBUG                                                       
 920         rq->clock_update_flags &= (RQCF_REQ_SKIP|RQCF_ACT_SKIP);                
 921         rf->clock_update_flags = 0;                                             
 922 #endif                                                                          
 923 }      
```

and lockdep_pin_lock() invokes this guys

```
4048 struct pin_cookie lock_pin_lock(struct lockdep_map *lock)                       
4049 {                                                                               
4050         struct pin_cookie cookie = NIL_COOKIE;                                  
4051         unsigned long flags;                                                    
4052                                                                                 
4053         if (unlikely(current->lockdep_recursion))                               
4054                 return cookie;                                                  
4055                                                                                 
4056         raw_local_irq_save(flags);                                              
4057         check_flags(flags);                                                     
4058                                                                                 
4059         current->lockdep_recursion = 1;                                         
4060         cookie = __lock_pin_lock(lock);                                         
4061         current->lockdep_recursion = 0;                                         
4062         raw_local_irq_restore(flags);                                           
4063                                                                                 
4064         return cookie;                                                          
4065 }                                                      
```

                         

-ss

**Pull request closed without merging**
