### PR TITLE
Muqss fixes 5.12

### PR DESCRIPTION
**Pull request by Mjasnik**
At some point, probably due to mainline changes, performance went south with LLC, SMT and MC, at least that's what my testing showed on Ryzen 1700.
Please take a look at these, should help to get back the performance.

### CODE REVIEW

**Comment by Mjasnik** [comment]
> Aaaand I had to revert it. On an Intel laptop, two things happen after resuming from suspend.
> 1. The system load sometimes shows some really high number in the millions
> 2. The system had a total freeze about 5 minutes after resuming requiring a hard power cycle.

Hmm, I have not seen this type of behavior, but...
I have reworked the code and I'm testing it on Ryzen as well as Intel laptop, so far it looks good and works as expected. If testing will not show any strange behavior, I'll force-push the changes once again.

> Some other observations, the performance between LLC on this patch and MC with stock MuQSS gives me the same clock time compiling Liquorix on the 5950x. Most likely that comes down to the fact that MuQSS still calculates the distance between cores correctly, so not having an RQ for each LLC isn't as bad as it could be.

CPU distances are always calculated / CPUs are ordered with LLC in mind regardless of sharing type.
Back in the day, I observed some small improvements with LLC, but currently, while testing, I did not see much of a difference between MC (one queue on Ryzen) and LLC (two queues on Ryzen).

**Comment by ckolivas** [comment]
MuQSS is in archive/maintenance mode and these changes are of questionable benefit and stability.

**Comment by Mjasnik** [comment]
I understand, I should not have not pushed the changes here after the announcement.
I have optimistic numbers, I'll talk to Damentz if he still wants this in zen.

**Comment by damentz** [comment]
@Mjasnik you can follow-up with a pull request for Zen Kernel.  I'm on Ryzen now so I'm interested in your improvements as long as they don't decrease stability overall.

Project:
https://github.com/zen-kernel/zen-kernel

Active branches as of this post:
https://github.com/zen-kernel/zen-kernel/tree/5.13/muqss
https://github.com/zen-kernel/zen-kernel/tree/5.14/muqss

When submitting a pull request, remember to submit it against the feature branch, _not_ master.

Zen Kernel matrix room: https://matrix.to/#/#zen-kernel:matrix.org
Zen Kernel IRC: #zen-kernel @ irc.oftc.net (plumbed through matrix)

Let's stay in touch through official channels I listed above.

**Pull request closed without merging**
